server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/modality?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: zjh
    password: 20040624ZJH
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  upload-root: D:/Download/Sensor_Spring
  in-memory-upload-limit: 268435456   # 256MB
  rate-limit:
    window-duration: 10s
    max-calls: 1000
    exit-on-exceed: true

logging:
  level:
    root: INFO
